on:
  workflow_dispatch:
jobs:
  my_jon:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: aosp
        key: ${{ runner.os }}
    - run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo
    - run: |
        mkdir aosp || true
        cd aosp
        export PATH=/home/runner/work/test/test/aosp/.repo/repo:$PATH
        repo init -b android-security-10.0.0_r75 -u https://android.googlesource.com/platform/manifest
